version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: supabase_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  supabase:
    image: supabase/postgrest
    container_name: supabase_postgrest
    environment:
      DB_URI: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      DB_SCHEMA: public
      JWT_SECRET: ${JWT_SECRET}  # Replace with your secret
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
